# Skycaptain: Forgejo Actions Updater
#
# SPDX-License-Identifier: BSD-3-Clause
#
---
name: Build Release

"on":
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      release_version:
        description: Release version (without leading "v")
        required: true
      release_notes:
        description: Release notes in markdown format
        required: true

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26"

      - name: Set release notes
        run: |
          RELEASE_NOTES_FILE=$(mktemp)
          echo "${{ github.event.inputs.release_notes }}" >> "${RELEASE_NOTES_FILE}"
          echo "GORELEASER_RELEASE_NOTES=${RELEASE_NOTES_FILE}" >> "${GITHUB_ENV}"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # renovate: datasource=github-releases depName=goreleaser/goreleaser versioning=semver
          version: "v2.16.0"
          args: release --clean --release-notes="${{ env.GORELEASER_RELEASE_NOTES }}"
